name: most_common_user_agents
description: A package for fetching the most common user agents
version: 1.0.0
repository: https://github.com/danemadsen/most_common_user_agents

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
