name: Extract JSON from HTML

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4

      - name: Extract JSON
        run: |
          python extract_json.py

      - name: Check for changes
        id: git-check
        run: |
          git add mobile.json desktop.json
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "should_commit=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "should_commit=true" >> $GITHUB_ENV
          fi

      - name: Commit data to repository
        if: env.should_commit == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Most Common User Agents"
          git push
