name: Extract JSON from HTML

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4

      - name: Extract JSON
        run: |
          python extract_json.py

      - name: Commit data to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mobile.json
          git add desktop.json
          git commit -m "Update Most Common User Agents" --allow-empty
          git push